#!/bin/sh
# Use this after reading the dumper tape with <chaos.*>

# Output files
for x in rel exe bin unv log; do
    find . -name "*.$x" -exec rm {} \; ;
done

# Output from monitor generation
rm -f chaos/monitor-sources/{parnew.mac,lnknew.ccl,bugstrings.txt}

# Generated by CVTUNV
rm -f chaos/midas/tnxdfu.mid

# Generated my EMACS
rm -f chaos/emacs/emacs.{chart,doc,odoc,wide-chart} chaos/emacs/teco.symbols
