#!/bin/sh
# Use this after reading the dumper tape with <chaos.*>
# By the way, the read20 to read "raw" tape (.tpr,.tpk) is https://github.com/hansliss/read20 which
# is different from e.g. https://github.com/brouhaha/tapeutils which is good for reading .tps tapes.
# Ho hum.

# Output files
for x in rel exe bin unv log; do
    find chaos -name "*.$x" -exec rm {} \; ;
done

# Output from monitor generation
rm -f chaos/monitor-sources/{parnew.mac,lnknew.ccl,bugstrings.txt}
rm -f chaos/vts/monitor-sources/{parnew.mac,lnknew.ccl,bugstrings.txt}

# Generated by CVTUNV
rm -f chaos/midas/tnxdfu.mid
rm -f chaos/vts/midas/tnxdfu.mid

# Generated my EMACS
rm -f chaos/emacs/emacs.{chart,doc,odoc,wide-chart} chaos/emacs/teco.symbols
