! Pandamonium configuration parameters
!
! Systemwide logical name definitions
!
DEFINE BLI: SYS:
DEFINE C: PS:<KCC-6.INCLUDE>
DEFINE CLISP: PS:<CLISP>
DEFINE DEFAULT-EXEC: SYSTEM:EXEC.EXE
DEFINE DEFAULT-MAILER: SYS:MM.EXE
DEFINE DOC: PS:<DOCUMENTATION>
DEFINE DOMAIN: PS:<DOMAIN>
DEFINE EDITOR: SYS:EMACS
DEFINE EMACS: ps:<chaos.vts.emacs>,ps:<chaos.emacs>,PS:<EMACS>
DEFINE FINGER: PS:<FINGER>
DEFINE FUN: PS:<GAMES>	
DEFINE HLP: PS:<HELP>
define info: ps:<info>
DEFINE INTERLISP: PS:<LISP>
DEFINE LISP: PS:<LISP>
DEFINE LOGIN-EXEC: SYSTEM:EXEC.EXE
DEFINE MACLISP: PS:<MACLISP>
DEFINE MAIL: PS:<MAIL>
DEFINE MAILQ: PS:<MAIL.QUEUE>
DEFINE MM: PS:<MM>
DEFINE MTA-DUMPER: MTA0:
DEFINE NEW: PS:<NEW-SUBSYS>,SYS:
DEFINE NRT: SYS:SETHOST.EXE
DEFINE OPR: CTY:
DEFINE PLOT: UNS:
DEFINE POBOX: PS:
DEFINE SAI: PS:<SAIL>
DEFINE SCRIBE: PS:<SCRIBE>
DEFINE SERR: PS:<SYSTEM-ERROR>
DEFINE SYS: ps:<chaos.vts.subsys>,ps:<chaos.subsys>,PS:<SUBSYS>,DOMAIN:,UNS:,UNIX-SYS:,SAI:,FUN:,HLP:,DSK:
DEFINE SYSTEM: PS:<SYSTEM>
DEFINE UNIX-ROOT: PS:<ROOT>
DEFINE UNIX-SYS: PS:<ROOT.BIN>,PS:<ROOT.USR.BIN>
DEFINE UNS: PS:<UNSUPPORTED>
DEFINE UNV: SYS:
!
! Other definitions
!
TIMEZONE -1
BATCH-BACKGROUND
DISABLE ACCOUNT-VALIDATION
!ENABLE TAPE-DRIVE-ALLOCATION
ENABLE WORKING-SET-PRELOADING
TAPE-RECOGNITION-ERRORS REGARD-AS-UNLABELED
NODE BV20
!DECNET ROUTER-ENDNODE
!ETHERNET 0 DECNET
