	UNIVERSAL TVTDEF
	SALL
	SEARCH MACSYM,MONSYM,PROLOG,TTYDEF
	SUBTTL TVT DATA DEFINITIONS

;PARAMETERS

NEGTM0==^D30000			;NEGOTIATION TIME-OUT (BETWEEN 1 & 2 OF THESE)
TMSNTT==^D500			;TIME PER CHARACTER OF TTMSG BEFORE FLUSHING

;NVT SPECIAL CHARACTERS

IACCH==377			;INITIATE COMMAND
DNTCH==376			;DON'T
DOCH==375			;DO
WNTCH==374			;WON'T
WILCH==373			;WILL
SBCH==372			;SB BEGINNING OF SUB NEGOTIATION
GACH==371			;GA GO AHEAD
ELCH==370			;EL ERASE LINE
ECCH==367			;EC ERASE CHARACTER
AYTCH==366			;AYT ARE YOU THERE?
AOCH==365			;AO ABORT OUTPUT
IPCH==364			;IP INTERRUPT PROCESS
BRKCH==363			;BREAK
DMCH==362			;DM DATA MARK
NOPCH==361			;NOP
SECH==360			;SE END OF SUBNEGOTIATION

;NVT OPTION DEFINITIONS

BINOPT==0			;BINARY
ECHOPT==1			;ECHO
RCNOPT==2			;RECONNECTION
SGAOPT==3			;SUPPRESS GA
NAMOPT==4			;NEGOTIATE MESSAGE SIZE
STSOPT==5			;STATUS
TMKOPT==6			;TIMING MARK OPTION
RCTOPT==7			;RCTE OPTION
ife TSBSW,<
WILOPT==10			;OFFSET FOR REQUESTS
MAXOPT==^D18			;ONLY 1 HALF WORD OF OPTION BITS
>
ifn TSBSW,<
LOCOPT==^d23			;Location option
TTPOPT==^d24			;Terminal type option
WSZOPT==^d31			;Window size option
WILOPT==WSZOPT+1		;OFFSET FOR REQUESTS
MAXOPT==^d36			;A full word of option bits
>

IFN VTSSW,<
; SUPDUP special chars
%TDORS==214			; Output reset
>

TTNETW=TTDEV
;BITS IN TTNETW
ifn VTSSW,<
DEFSTR NVTYP,TTNETW,2,2		;99 Line type
.TYNNV==0			;99 New NVT
.TYONV==1			;99 Old NVT
.TYSUP==2			;99 SUPDUP terminal
>
DEFSTR PTITC,TTNETW,5,3		;COUNT, SYNC-INS
NV%WKS==1B8			;RCTE WAKEUP SEEN
MSKSTR NVWKS,TTNETW,NV%WKS
NV%RCS==1B9			;RCTE CHAAGE IN STATE
MSKSTR NVRCS,TTNETW,NV%RCS
ife VTSSW,< ;; This is replaced by NVTYP
NV%NNV==1B10			;NEW STYLE NVT
MSKSTR NVNNV,TTNETW,NV%NNV
>
NV%TMO==1B11			;NEGOTIATION TIME-OUT STARTED
MSKSTR NVTMO,TTNETW,NV%TMO
DEFSTR NVSTP,TTNETW,14,3	;CURRENT NVT STATE
;THE FOLLOWING NVT STATES ARE STORED IN TTNETW BITS 12-14 (NVSTP)
.DFWIL==1			;DEFERRED WILL
.DFWNT==2			;DEFERRED WONT
.DFDO==3			;DEFERRED DO
.DFDNT==4			;DEFERRED DONT
.DFIAC==5			;DEFERRED IAC
IFN VTSSW,<
.DF300==6			;99 SUPDUP - 300 received
.DFCLC==7			;99 SUPDUP - reading console location
ifn TSBSW,<
;.DFSB==10			;@@@@ only 3 bits in NVSTP!
if1,<printx ?VTSSW==1 can not have TSBSW==1 - only 3 bits in NVSTP>
>
>
ife VTSSW,<
ifn TSBSW,<
.DFSB==6			;Deferred SB (subnegotiation value being collected)
>
>
NV%GAB==1B15			;BIT IN TTNETW -- SUPPRESS GO-AHEAD
MSKSTR NVGAB,TTNETW,NV%GAB
NV%CRI==1B16			;BIT IN TTNETW, LAST CHAR IN WAS CR
MSKSTR NVCRI,TTNETW,NV%CRI
NV%CRP==1B17			;BIT IN TTNETW -- LAST CHAR OUT WAS CR
MSKSTR NVCRP,TTNETW,NV%CRP

TTBRKC=TTDDLN			;BREAK CLASSES FOR NVT'S
DEFSTR PBRCT,TTBRKC,8,9 ;BITS 0-8: OUTSTANDING BREAK COUNT
				;BITS 9-17: LAST RCTE COMMAND SENT
				;BITS 18-35: LAST BREAK CLASSES SENT
MAXBRC==777


ife TSBSW,<
NVTOPF=TTDDLN+1			;LH -- BIT FOR EACH OPTION IN PROGRESS
				;RH -- BIT FOR RESULT OF EACH OPTION
>
ifn TSBSW,<
;; The above single word actually has the following FOUR fields, which works
;; since WILOPT (the max implemented option+1) is just 10. But when doing
;; options like ^d31 (window size), we need four words.
NVTODP==TTDDLN+1		;DO options being negotiated
NVTOWP==NVTODP+1		;WILL options being negotiated
NVTODR==NVTOWP+1		;DO options enabled (result)
NVTOWR==NVTODR+1		;WILL options enabled (result)
NVSBLN==NVTOWR+1		;SB buffer len
NVSBPT==NVSBLN+1		;SB buffer ptr
NVSBBF==NVSBPT+1		;SB buffer
NVSBBX==5			;max len of buffer (5 words of 4 8-bit bytes)
NVSBBB==<NVSBBX*4>		;bytes
if2,<ifl TVTLEN-<NVSBBF+NVSBBX>,<printx ?TVTLEN does not match NVSBBF>> ;double-check

;; Subnegotiation request circular list (cf STG: SBCEMX, SBCELN, SBCLST)
sbcrix==0			; SBCRIX - the read index
sbcwix==1			; SBCWIX - the write index
sbcnts==2			; offset of subsequent entries 
; The first word of each entry is a "header" (9 bits just to make it legible in debug):
edefstr(sbtty,0,8,9)		;CTRLTT of the request TVT
edefstr(sbjob,0,17,9)		;JOBNO of the request TVT
edefstr(sbopt,0,26,9)		;Telnet option
edefstr(sblen,0,35,9)		;The length of the value in the following buffer

;TTYLOC definitions - MUST MATCH FNGDEF!
;User block definition - contains job number and starting time
TL%JOB==777000,,000000		;Job number
TL%STM==000777,,777777		;Job starting time (low 27 bits)

;Terminal entry definitions
.TDWHO==0			;Who has this entry
.TDLKD==1			;This entry locked - don't use (-1 = locked)
.TDLOC==2			;What the string location is
 .TDLLN==6			;How many words for string
.TDLEN==.TDLOC+.TDLLN		;Length of each entry
>

;TVTLEN IS DEFINED IN TTYDEF
; and remember to recompile TTYSRV when TVTLEN is changed.

	END
