@enable
@define rel: dsk:,<chaos.monitor-sources>,sys:
@define unv: <chaos.monitor-sources>,sys:
@DEFINE exc: DSK:,<exec-sources>,<TOOLS.EXEC-MODS>
@COMPILE exc:EXECDE.MAC+exc:EXECGL.MAC EXECGL
@COMPILE exc:EXECPR.MAC EXECPR
@COMPILE exc:WHEXEC.MAC+exc:EDEXEC.MAC+exc:EXECVR.MAC EXECVR
@COMPILE exc:EXECF3.MAC+exc:EXECCA.MAC EXECCA
@COMPILE exc:EXEC0.MAC EXEC0
@COMPILE exc:EXEC1.MAC EXEC1
@COMPILE exc:EXECSE.MAC EXECSE
@COMPILE exc:EXECMT.MAC EXECMT
@COMPILE exc:EXECP.MAC EXECP
@COMPILE exc:EXECIN.MAC EXECIN
@COMPILE exc:EXEC2.MAC EXEC2
@COMPILE exc:EXEC3.MAC EXEC3
@COMPILE exc:EXEC4.MAC EXEC4
@COMPILE exc:EXECED.MAC EXECED
@COMPILE exc:EXECCS.MAC EXECCS
@COMPILE exc:EXECQU.MAC EXECQU
@COMPILE exc:EXECSU.MAC EXECSU
@COMPILE exc:MICPRM.MAC MICPRM
@COMPILE exc:EXECMI.MAC EXECMI
@COMPILE exc:EXECCE.MAC EXECCE
@R LINK
*EXEC/SAVE, -
*/SET:.HIGH.:200000, -
*/SYMSEG:HIGH, -
*TTY:/LOG/LOGL:5, -
*EXECGL,EXECPR,EXECVR,EXEC0,EXEC1,EXECSE,EXECMT,EXECP,EXECIN, -
*EXEC2,EXEC3,EXEC4,EXECED,EXECCS,EXECQU,EXECSU, -
*EXECCA, -
*MICPRM,EXECMI, -
*exc:EXECPM,exc:EXECPS,exc:EXECPI,exc:EXECPC,exc:EXECPX,exc:EXECPU, -
*EXECCE, -
*rel:MACREL.REL
*/COUNTER/GO
@EXPUNGE
@RUN EXEC
*Y
@FILDDT
*ENABLE PATCHING
*GET EXEC.EXE
*PCDO 42/<SETZM PCLMID>
*
